name: Update prod

on:
  workflow_dispatch:

jobs:
  copy-main-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup crane
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c

      - name: Copy Staging to Prod
        run: crane tag ghcr.io/${{ github.repository }}:stg prod